### ISSUE TITLE
Feature: Coupling with projects

### ISSUE THREAD

**Issue by koppor** [takanome-dev/assign-issue-action#239]
### Type of feature

💡 Feature

### Current behavior

In our project, we use GitHub's projects to provide a more detailed tracking of issues.

![image](https://github.com/user-attachments/assets/fedaf888-6408-45d6-8311-ad1ab26cbf58)

If a student is assigned, the state of the issue should move to "Assigned". If the student is unassigned, the state should go back to "Free to take"

### Suggested solution

It would be nice, if the action could change the values of the (custom) "Status" field of a project.

I image a configueaton like:

```yaml
unassigned:
  - project: someId
    field: Status
    newValue: Free to take
  - project: AnotherId
    field: Status
    newValue: Free to take
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs
